version: "3.3"

services:
  app:
    container_name: vote-web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      - PORT=8080
    restart: always
    ports:
      - "8080:8080"
